posts_list:
    path: '/list'
    defaults: 
        _controller: swe_app.post.controller:listAction
        _template: post/list.html.twig 
    methods: [GET]
post_show:
    path: '/show/{id}'
    defaults: 
        _controller: swe_app.post.controller:showAction
        _template: post/show.html.twig 
    methods: [GET]

post_new:
    path: /new
    defaults: 
        _controller: swe_app.post.controller:crudAction
        _template: post/crud.html.twig  
    methods: [GET,POST]
post_edit:
    path: '/{id}/edit'
    defaults: 
        _controller: swe_app.post.controller:crudAction
        _template: post/crud.html.twig   
    methods: [GET,PUT]
post_delete:
    path: '/delete/{id}'
    defaults: 
        _controller: swe_app.post.controller:deleteAction
        _redirect_to : posts_list
    methods: [GET]