<?php

namespace AppBundle\Repository\Interfaces;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface UserRepositoryInterface 
{
}
