services:
    swe_app.post.form.handler:
        class: Swe\CrudBundle\Form\Handler\ResourceFormHandler
        calls:
           - [setNewResourceFormHandlerStrategy, ['@swe_app.new_post.form.handler.strategy']]
           - [setUpdateResourceFormHandlerStrategy, ['@swe_app.update_post.form.handler.strategy']]
           - [setConfiguration, ['@swe_app.post.configuration']]

    swe_app.new_post.form.handler.strategy:
        class: AppBundle\Form\Handler\NewPostFormHandlerStrategy
        arguments:
            - "@translator"
            - "@swe_app.post.manager"
            - "@form.factory"
            - "@router"

    swe_app.update_post.form.handler.strategy:
        class: AppBundle\Form\Handler\UpdatePostFormHandlerStrategy
        arguments:
            - "@translator"
            - "@swe_app.post.manager"
            - "@form.factory"
            - "@router"


    swe_app.user.form.handler:
        class: Swe\CrudBundle\Form\Handler\ResourceFormHandler
        calls:
           - [setNewResourceFormHandlerStrategy, ['@swe_app.new_user.form.handler.strategy']]
           - [setUpdateResourceFormHandlerStrategy, ['@swe_app.update_user.form.handler.strategy']]
           - [setConfiguration, ['@swe_app.user.configuration']]

    swe_app.new_user.form.handler.strategy:
        class: AppBundle\Form\Handler\NewUserFormHandlerStrategy
        arguments:
            - "@translator"
            - "@swe_app.user.manager"
            - "@form.factory"
            - "@router"

    swe_app.update_user.form.handler.strategy:
        class: AppBundle\Form\Handler\UpdateUserFormHandlerStrategy
        arguments:
            - "@translator"
            - "@swe_app.user.manager"
            - "@form.factory"
            - "@router"
            
            
    swe_app.post_search.form:
            class: AppBundle\Form\Type\ActorSearchFormType
            tags:
                - { name: form.type, alias: actor_search }
