services:
    swe_app.post.repository:
        class: AppBundle\Repository\PostRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle\Entity\Post']
        lazy: true
    swe_app.user.repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle\Entity\User']
        lazy: true